import Link from "next/link";
import { notFound } from "next/navigation";
import { caseStudies, getCaseStudy } from "@/content/case-studies";
import { FinalCta, PlaceholderVisual } from "@/components/shared/site-components";
import { Reveal } from "@/components/shared/reveal";
export function generateStaticParams() { return caseStudies.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }) { const study = getCaseStudy(params.slug); return study ? { title: `${study.title} — Cerato Systems`, description: study.summary, openGraph: study.socialImage ? { images: [study.socialImage] } : undefined } : {}; }
export default function CaseStudyPage({ params }) { const study = getCaseStudy(params.slug); if (!study) notFound(); const nextStudy = study.nextCaseStudySlug && getCaseStudy(study.nextCaseStudySlug); return <><article className="case-study container"><Link className="back-link" href="/customers">← Back to Customers</Link><p className="eyebrow">{study.eyebrow || study.industry}</p><h1>{study.title}</h1><p className="case-summary">{study.summary}</p>{study.facts?.length > 0 && <dl className="facts">{study.facts.map(({ label, value }) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}{study.heroImage ? <img className="case-hero-image" src={study.heroImage} alt={study.heroImageAlt || "Case study product visual"} /> : <PlaceholderVisual label="CASE STUDY HERO VISUAL" />}<CaseBlock heading={study.challenge?.heading} body={study.challenge?.body} /><CaseBlock heading={study.goal?.heading} body={study.goal?.body} /><CaseBlock heading={study.solution?.heading} body={study.solution?.body} />{study.sections?.map((section) => <CaseBlock key={section.heading} {...section} />)}{study.outcomes?.length > 0 && <section className="outcomes"><h2>Outcomes</h2>{study.outcomes.map((outcome) => <div key={outcome.heading}><h3>{outcome.heading}</h3><p>{outcome.body}</p></div>)}</section>}{study.technology?.length > 0 && <section className="case-technology"><h2>Technology</h2><div>{study.technology.map((technology) => <span key={technology}>{technology}</span>)}</div></section>}{study.testimonial && <blockquote className="testimonial">“{study.testimonial.quote}”{(study.testimonial.name || study.testimonial.role) && <footer>{[study.testimonial.name, study.testimonial.role].filter(Boolean).join(", ")}</footer>}</blockquote>}{nextStudy && <Link className="next-study" href={`/customers/${nextStudy.slug}`}><span>Next customer story</span><strong>{nextStudy.title} →</strong></Link>}</article><FinalCta title="Have an operation that has outgrown its tools?" body="We build custom software around workflows that generic systems cannot quite fit." /></>; }
function CaseBlock({ heading, body, bullets, image, imageAlt }) { if (!body?.length && !bullets?.length && !image) return null; return <Reveal as="section" className="case-block"><h2>{heading}</h2>{body?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{bullets?.length > 0 && <ul>{bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}{image && <img src={image} alt={imageAlt || "Case study visual"} />}</Reveal>; }
