/** Reusable customer-story records. Optional fields disappear when absent. */
export const caseStudies = [{
  slug: "transportation-operations-platform",
  title: "From spreadsheets and messaging apps to one operational platform",
  eyebrow: "Passenger transportation", industry: "Passenger transportation", anonymousClient: true,
  summary: "A custom system that brought passenger booking, dispatch, fleet operations, driver workflows, financial reconciliation, and reporting into one connected platform.",
  coverLabel: "TRANSPORTATION CASE STUDY COVER", coverImage: "/case-studies/transportation-operations-hero.png", cardFacts: ["~50 buses", "~30 drivers", "Live in production", "End-to-end custom system"],
  meta: { title: "Transportation Operations Platform — Cerato Systems", description: "How Cerato Systems replaced spreadsheets, messaging apps, and manual transportation workflows with a custom operational platform spanning booking, dispatch, fleet, drivers, financial reconciliation, and reporting.", ogTitle: "From spreadsheets and messaging apps to one operational platform", ogDescription: "A custom operational system built around the day-to-day complexity of a passenger transportation company." },
  facts: [{ label: "Operation", value: "~50 buses" }, { label: "Driver network", value: "~30 drivers" }, { label: "Initial build", value: "~6 months" }, { label: "Status", value: "Live in production" }],
  heroVisual: { label: "SCREENSHOT 1 — DAILY OPERATIONS / DISPATCH OVERVIEW", image: "/case-studies/transportation-operations-hero.png", alt: "Anonymized passenger transportation booking, dispatch, and operations interfaces" },
  heroBody: ["A passenger transportation company was running critical parts of its operation through spreadsheets, messaging apps, manual calculations, and knowledge carried by the people managing the business.", "Cerato Systems designed and built a custom platform that brought passenger booking, daily dispatch, fleet and driver operations, trip execution, financial reconciliation, ticket control, and reporting into one connected system."],
  challenge: { eyebrow: "The challenge", heading: "The operation had outgrown the tools holding it together.", body: ["Passenger transportation looks straightforward from the outside: publish a schedule, sell a seat, assign a bus, and complete the trip. Behind the scenes, the operation is a dense network of dependencies.", "Passengers need to be connected to the correct departure and seat. Vehicles and drivers need to be available at the right time. Routes can span multiple stops and countries. Trips generate mileage, fuel records, cash, expenses, ticket records, manifests, and travel documents. Last-minute changes have to be reflected across the operation without losing track of what changed.", "For this company, much of that work was being coordinated through Excel, Viber, WhatsApp, a calculator, and manual communication. Information lived in different places, calculations had to be repeated, and important operational knowledge often depended on the person handling the task.", "At a fleet of roughly 50 buses and a network of around 30 drivers, that approach placed a significant amount of operational work on the company owner and office team. Running the business meant constantly checking, calculating, reconciling, calling, messaging, and making sure information in one place still matched information somewhere else."], callout: "The problem was not a lack of software. It was that the operation had no single system built around the way the business actually worked." },
  goal: { eyebrow: "The goal", heading: "Build around the operation instead of forcing the operation into another tool.", body: ["The goal was not to digitize one isolated task.", "It was to understand how the company actually operated from the moment a passenger searched for a trip through to the moment a completed journey was reconciled — then build a system around those workflows.", "That meant treating booking, dispatch, drivers, vehicles, seats, money, fuel, ticket stock, packages, and reporting as parts of the same operation rather than separate software problems.", "The system also had to account for the details that generic software often ignores: return journeys, transfer departures, seat allotments, multiple vehicles on the same departure, resource conflicts, international mileage, driver settlement, physical ticket serials, and changes that happen while the operation is already moving."], callout: "One system. Different roles. One source of operational truth." },
  solution: { eyebrow: "The solution", heading: "A custom operational platform connecting the business from booking to reconciliation.", body: ["Cerato Systems built an end-to-end application with interfaces for passengers, office operations, management, and drivers.", "Instead of replacing one spreadsheet with another isolated tool, the platform connects the major workflows of the transportation business through shared operational data.", "A reservation created through the public booking experience becomes part of the same operational system used to assign seats, plan departures, allocate vehicles and drivers, manage trips, reconcile money, and generate reports.", "The result is a system designed around the lifecycle of the work rather than around the boundaries of individual departments or generic software products."], capabilities: ["Passenger booking", "Reservations & seats", "Routes & departures", "Daily dispatch", "Fleet & drivers", "Driver trip workflow", "Mileage & fuel", "Financial reconciliation", "Ticket inventory", "Packages", "Operational reporting"] },
  sections: [
    { eyebrow: "Passenger booking", heading: "Booking is connected directly to the operation behind it.", body: ["Passengers can search available trips, select a journey, reserve seats, book return travel, and receive confirmation through the public-facing application.", "Behind that interface, the booking is not treated as a disconnected ecommerce transaction. It becomes an operational record tied to the departure, route, passenger, seat capacity, and the rest of the transportation workflow.", "The system supports route-stop sequencing, segment-level fares, one-way and return journeys, different passenger fare types, transfers, linked departures, and seat availability rules.", "That connection between the customer-facing experience and the internal operation removes the need to recreate booking information manually in a separate back-office process."], visual: { label: "SCREENSHOT 2 — PASSENGER BOOKING", image: "/case-studies/transportation-passenger-booking.png", alt: "Anonymized passenger booking interface showing available departures", caption: "Passenger booking feeds directly into the same system used by the operations team." } },
    { eyebrow: "Daily operations", heading: "The software reflects how transportation work actually happens.", body: ["The operational side of the system brings routes, departures, reservations, passengers, vehicles, and drivers into one working environment.", "For each day, the team can see what is running, assign vehicles and drivers, manage additional buses when demand requires them, and move passengers when operational changes make that necessary.", "The system checks for overlapping vehicle and driver assignments rather than relying on someone to remember every conflict manually.", "Seat assignment is also connected to the underlying departure, vehicle layout, capacity, and allotment rules. The objective is not simply to store data — it is to prevent operational mistakes before they become problems on the road."], bullets: ["Daily vehicle and driver allocation", "Resource-overlap checks", "Multiple buses on a departure", "Passenger reassignment", "Seat layouts and availability", "Seat allotments", "Regular and special departures", "Transfer / linked departures", "One-way and return passenger lifecycle"], visual: { label: "SCREENSHOT — DAILY DISPATCH", image: "/case-studies/transportation-daily-operations.png", alt: "Anonymized dispatch view for assigning vehicles and drivers to daily departures", caption: "Daily dispatch connects departures, passenger demand, vehicles, and drivers in one operational workflow." } },
    { eyebrow: "Driver operations", heading: "The trip continues inside the system after the bus leaves the station.", body: ["Drivers have a dedicated workflow for the journeys assigned to them.", "During and after a run, the system can capture the information needed to close the trip operationally: mileage, fuel, passenger counts, cash, expenses, and travel-order information.", "This matters because the physical journey is only one part of completing a transportation service. The business also needs a reliable record of what happened during that journey and what needs to be reconciled afterward.", "The driver interface keeps that process connected to the same departure and operational data already used by the office team."], subheading: "Built for work that happens on the road.", supportingCopy: "Driver workflows cannot assume a perfect office connection. The driver application includes offline-oriented behavior that can preserve selected reads and queue writes locally when connectivity is unavailable, allowing important trip work to remain practical in real operating conditions. Once connectivity is available again, queued work can continue back into the central system.", visual: { label: "SCREENSHOT 3 — DRIVER TRIP / FINANCIAL SETTLEMENT", caption: "Drivers complete trip records in the same system used by the office and management teams." } },
    { eyebrow: "Flexible access", layout: "split", heading: "The operation stays accessible wherever the work happens.", body: ["Transportation operations do not happen only behind a desk.", "Schedules change, vehicles are on the road, staff move between locations, and important information may be needed when a computer is not nearby.", "The application was built to remain practical across different screen sizes, allowing key operational information and workflows to be accessed from a phone as well as a desktop computer.", "That means the system can stay useful in the office, at the station, next to a vehicle, or while someone responsible for the operation is away from their desk."], bullets: ["Operational information is not locked to one office computer.", "Staff can stay connected to the same centralized system while moving between locations.", "Important information can be checked without waiting to return to a desk.", "The application adapts to the way transportation work actually happens."], visual: { label: "SCREENSHOT 4 — FULL APPLICATION ON A PHONE", image: "/case-studies/transportation-mobile-operations.png", alt: "Anonymized mobile operations schedule view", caption: "The same operational system remains useful away from the desk.", orientation: "phone" } },
    { eyebrow: "Financial control", heading: "Operational data and money are reconciled in the same workflow.", body: ["One of the most important parts of the project was improving control around the money and records associated with each trip.", "When cash, passenger counts, fuel, expenses, and ticket records are managed through separate conversations and calculations, discrepancies can be difficult to detect and even harder to trace back to the trip that created them.", "The platform ties financial and operational information back to the journey itself. Driver settlement, passenger counts, collected cash, fuel entries, expenses, and related records can be reviewed as part of a structured trip-closing process.", "This gives management a much clearer basis for checking what was expected against what was recorded, and reduces the opportunity for mistakes, omissions, or unexplained discrepancies to pass unnoticed."], callout: "The system does not just record what happened. It gives the business a way to verify it." },
    { eyebrow: "Beyond the core trip", heading: "The smaller operational details were part of the system too.", body: ["A real transportation business contains important workflows that rarely appear in generic booking software.", "The platform includes supporting tools for the operational details that still need to be controlled every day."], subheading: "A departure remains manageable after the booking is made.", supportingCopy: "The operations team can work directly with the passengers attached to a departure, review boarding and payment states, inspect passenger records, and take the actions required as the journey approaches. That keeps the operational passenger list connected to the same departure data that originated earlier in the booking process.", visual: { label: "SCREENSHOT — DEPARTURE PASSENGER CONTROL", image: "/case-studies/transportation-departure-control.png", alt: "Anonymized departure passenger-control view", caption: "Passenger records remain connected to the departure, including boarding, payment status, and operational actions." }, groups: [["Physical ticket stock", "Physical ticket books can be managed through depot batches and serial-number ranges, with validation around allocation and stock."], ["Packages", "Package transportation can be recorded alongside the passenger operation instead of being tracked separately through messages or paper."], ["Manifests and operational documents", "Passenger manifests and other operational outputs can be generated directly from system data, including spreadsheet and image-based exports where required by the workflow."], ["Mileage and travel orders", "The system can produce mileage and travel-order reporting from the data captured through the actual trip workflow."], ["Domestic / international mileage", "Routes can distinguish Serbian and non-Serbian mileage, supporting operational records for journeys that cross national borders."]] },
    { eyebrow: "Built for complexity", heading: "Simple screens sit on top of complicated business rules.", body: ["Much of the engineering work in this project is invisible in a screenshot.", "Transportation operations contain dependencies that have to be modeled correctly for the interface to remain simple: which route segment a passenger is travelling, which seats are actually available, whether a vehicle or driver is already committed elsewhere, how a return journey relates to the outbound booking, and how one departure changes when more than one bus is required.", "The platform turns those rules into validations and workflows so the people running the operation do not have to reconstruct the logic manually each time."], bullets: ["Segment-aware routes and fares", "Seat capacity and allotment rules", "Multi-bus dispatch", "Vehicle / driver conflict checks", "Round-trip passenger lifecycle", "Transfer and linked departures", "International mileage separation", "Trip-level financial reconciliation", "Physical ticket serial controls", "Driver offline-oriented workflows", "Operational document generation"], closing: "The complexity stays in the system so the workflow can stay understandable for the person using it." },
    { eyebrow: "Engineering", heading: "Designed and built end to end.", body: ["The project was built as a complete software system rather than a collection of disconnected interfaces.", "Cerato Systems was responsible for the application architecture, frontend, backend business logic, data model, integrations, operational workflows, exports, and ongoing development.", "The public-facing application is built with Next.js, React, and TypeScript. The operational backend is implemented as a custom Odoo module in Python with PostgreSQL as the database.", "The system connects the public booking experience to the operational back office through server-side integration, while email services support passenger confirmation workflows.", "The technology was selected and shaped around the needs of the operation. The important outcome is not the framework list — it is that the customer-facing experience, internal workflows, business rules, and data all operate as one system."], technologies: ["Next.js", "React", "TypeScript", "Python", "Odoo", "PostgreSQL", "JSON-RPC integrations", "Email delivery", "XLSX / image exports", "PWA / offline-oriented driver workflow"], ownership: ["Product / workflow design", "Frontend engineering", "Backend engineering", "Data modeling", "Business-rule implementation", "Integrations", "Operational exports", "Responsive interfaces", "Production implementation", "Ongoing maintenance & development"] }
  ],
  outcome: { eyebrow: "The outcome", heading: "The business moved from fragmented tools to one operational system.", body: ["The platform is now live in production and continues to support the company's day-to-day operation.", "Passenger information, routes, departures, fleet resources, driver workflows, trip records, financial reconciliation, ticket control, and reporting no longer need to live across the same collection of spreadsheets, messages, calculations, and disconnected processes that existed before.", "The most important change is operational leverage.", "Work that previously required the owner and staff to manually connect information across different tools can now happen through structured workflows inside one system. Management has better visibility into what is happening, stronger control over operational and financial records, and a more reliable foundation for running the business.", "For the owner in particular, the system reduces the amount of repetitive operational coordination that has to be carried personally, creating more room to focus on the company rather than continuously holding its processes together."], bullets: ["One connected operational system", "Live in daily production", "Public booking connected to back-office operations", "Centralized passenger, route, fleet, driver, and trip data", "Structured trip and financial reconciliation", "Stronger visibility and operational control", "Less dependence on manual coordination", "Software maintained and extended as the operation evolves"] },
  closing: { eyebrow: "What this project represents", heading: "Custom software is most valuable when the business has outgrown generic tools.", body: ["This project is not valuable because transportation companies need another booking application.", "It is valuable because the business had developed its own operational rules, exceptions, responsibilities, and ways of working — and the tools around it were no longer enough to manage that complexity cleanly.", "Cerato Systems turned those workflows into software built around the operation.", "That is the kind of problem we are built to solve."] }
}, {
  slug: "navixor-construction-operations-platform",
  title: "From site paperwork to one construction operations system",
  eyebrow: "Construction operations", industry: "Construction", anonymousClient: true,
  summary: "A custom platform connecting site logs, workers, machinery, fuel, work hours, approvals, and reporting across construction sites.",
  coverLabel: "NAVIXOR CASE STUDY COVER", coverImage: "/case-studies/navixor-dashboard.png", cardFacts: ["Multi-site operations", "Field and office workflows", "Role-based access", "Custom platform"],
  meta: { title: "Navixor Construction Operations Platform — Cerato Systems", description: "How Cerato Systems designed Navixor, a custom construction operations platform for site logs, work hours, machinery, fuel, approvals, and reporting.", ogTitle: "From site paperwork to one construction operations system", ogDescription: "A custom operational system connecting field teams, supervisors, and management across construction sites." },
  facts: [{ label: "Industry", value: "Construction" }, { label: "Operation", value: "Multi-site" }, { label: "Users", value: "Field teams to management" }, { label: "System", value: "Custom web platform" }],
  heroVisual: { label: "NAVIXOR DASHBOARD", image: "/case-studies/navixor-dashboard.png", alt: "Navixor construction operations dashboard showing site logs, workers, machinery, work hours, and fuel consumption" },
  heroBody: ["For a construction-industry client, Cerato Systems designed Navixor: one system replacing paper site logs, machinery, fuel and work-hour records, and approvals that previously waited for people to meet in person.", "The platform gives field teams a practical way to record work, while supervisors and management see the operational state of every site from one connected system."],
  challenge: { eyebrow: "The challenge", heading: "The company had software, but the operation still ran on paper, spreadsheets, and calls.", body: ["People were not avoiding record-keeping. The problem was the rhythm of construction work: teams are on site, the information they need changes through the day, and the office is often elsewhere.", "Site data was not entered regularly, so the backlog built up until periodic reporting — especially annual fuel and material reporting. Site logs, trip orders, work hours, and machinery servicing information were spread across notebooks, spreadsheets, phone calls, and individual knowledge.", "Approvals became a bottleneck when a supervisor needed to sign a site log that was physically on site. Management had no real-time view of workers, sites, or idle machinery without calling around."], callout: "The problem was not a missing screen. It was an operational chain that broke between the site and the office." },
  goal: { eyebrow: "The goal", heading: "Make operational records easy to capture in the field and useful for decisions in the office.", body: ["The goal was to create one practical system for the people doing the work, the supervisors reviewing it, and the managers responsible for the wider operation.", "That meant building around four clear entities — sites, machinery, workers, and companies — rather than creating another overloaded menu of unrelated tools.", "The first priority was the operational backbone: a digital site log and supervisor approval workflow. Everything else could then connect to the same source of truth."], callout: "Field teams record what happened. Supervisors review it. Management sees what needs a decision." },
  solution: { eyebrow: "The solution", heading: "A role-based construction operations platform built around the real workday.", body: ["Navixor gives each role a focused view of the operation. Field teams can enter the required information from a phone in a few steps, when they have time. Supervisors can review and sign from wherever they are. Management sees the state of the company and the work that needs attention.", "Instead of making people reconstruct the operation from calls, paper, and separate files, the system connects site logs, workers, machinery, fuel, work hours, approvals, and reporting through shared operational data."], capabilities: ["Digital site logs", "Supervisor review and approval", "Worker and work-hour records", "Machinery status and service planning", "Fuel records and reporting", "Role and location-based access", "Operational dashboards", "Exports and reporting"] },
  sections: [
    { eyebrow: "Operational control", heading: "The dashboard turns follow-up work into clear decisions.", body: ["The main view is intentionally organized around what needs attention, not around charts. Management can immediately see site logs waiting for approval, requested changes, work hours ready for payroll, and machinery that has been idle for too long.", "Below that, the same dashboard shows the state of active sites: workers checked in, logs completed, machinery in use, and fuel added. It replaces the morning round of calls with a shared, current picture of the operation."], visual: { label: "NAVIXOR OPERATIONS DASHBOARD", image: "/case-studies/navixor-dashboard.png", alt: "Navixor dashboard for construction operations", caption: "A single operational view for approvals, sites, machinery, work hours, and fuel." } },
    { eyebrow: "Designed for adoption", heading: "Faster than paper, or it will not be used.", body: ["The first version of the previous application did not fail because of technology. It failed because it did not fit the people expected to use it.", "Navixor removes every field that is not legally or operationally necessary. Where the system already knows the information, it fills it in. A trip order can retain its full legal structure while leaving the driver with only a small number of fields to complete.", "The system also allows field teams to record past dates. Rather than punishing a late entry, it makes it possible to capture complete information when the team has time."], bullets: ["Practical phone-first entry", "Pre-filled operational information", "Past-date entry when work allows", "Quiet visual signals for missing site logs", "Role-specific views with less training and fewer errors"] },
    { eyebrow: "Access and roles", heading: "Every role sees the work it needs — and not the work it does not.", body: ["The platform was designed around the jobs of management, site managers, supervisors, and drivers. A supervisor sees only the logs that require their signature. A driver does not see payroll data. Management has the cross-company picture needed to make decisions.", "This keeps the interface clear while protecting sensitive operational information and avoiding unnecessary complexity for field users."], visual: { label: "NAVIXOR ACCESS EXPERIENCE", image: "/case-studies/navixor-access.png", alt: "Navixor login screen showing a focused, accessible entry point for users", caption: "A focused access experience supports role-based workflows from any device." } },
    { eyebrow: "Operational records", heading: "Sites, machinery, work hours, and fuel stay connected.", body: ["Each part of the system replaces a manual coordination task. Site managers and management can see who runs a site, when its log was entered, and whether it is under review, returned, or approved. Machinery status and engine hours make upcoming service needs visible before an idle machine becomes a surprise.", "Weekly work-hour records support payroll preparation without manually adding notebooks. Fuel consumption can be reviewed by month and exported for reporting, removing the multi-day reconstruction that annual reporting once required."], groups: [["Sites", "See site managers, log status, pending reviews, and missing entries."], ["Machinery", "Track availability, engine hours, servicing needs, and idle equipment."], ["Work hours", "Maintain weekly records by worker and site for payroll preparation."], ["Fuel", "Record fuel activity, review consumption, and export reports from live operational data."]] },
    { eyebrow: "What scales", heading: "The same principles become more valuable as the operation grows.", body: ["The more people, machines, and sites a company coordinates, the more expensive each delayed or missing record becomes. The same structure can extend across companies, departments, regions, subcontractors, and years of operational history.", "A custom system can connect to ERP, accounting, payroll, GPS or machinery telematics, and fuel-card systems. It can automate hour calculations, recurring reports, and alerts for unusual fuel consumption or equipment downtime."], bullets: ["ERP, accounting, payroll, telematics, and fuel-card integrations", "Automated calculations, reporting, and alerts", "Multi-company, regional, and subcontractor structures", "Role and location-based permissions", "Custom forms, terminology, and approval workflows"] },
    { eyebrow: "How we work", heading: "Start with the operational backbone, then grow from there.", body: ["The work began with discovery: understanding the business, the people involved, and the tools already in use. We mapped roles and data flows, then designed a clickable prototype for the critical workflows before development began.", "The first implementation focused on the system backbone and can be introduced to one site or department first. From there, integrations and automation can be added in the order that brings the most value to the operation."], bullets: ["Discovery and operational mapping", "User research and information architecture", "Prototype validation with real users", "A focused first release", "Phased rollout, integrations, and automation"] }
  ],
  outcome: { eyebrow: "The outcome", heading: "A shared operational picture, without the paperwork chase.", body: ["Navixor replaces fragmented operational records with one system that can be used in the field and understood in the office.", "Instead of waiting for documents to travel, chasing people for updates, or reconstructing reports from past records, teams can work from current information connected to the site, machine, worker, and company it belongs to.", "The result is not just digitized paperwork. It is a more reliable way to run a distributed operation."], bullets: ["Faster site-log capture and approval", "Better visibility across sites and machinery", "Less manual reporting and reconciliation", "Focused role-based workflows", "A foundation for integrations and automation"] },
  closing: { eyebrow: "What this project represents", heading: "Custom software works when it fits the work people actually do.", body: ["Navixor is not an off-the-shelf product. It is an example of how Cerato Systems approaches operational complexity: understand where the information is created, who needs it, where the chain breaks, and what should happen next.", "That approach applies wherever people work across locations, depend on approvals, and spend too much time holding disconnected tools together."] }
}, {
  slug: "case-study-coming-soon",
  status: "placeholder",
  featured: false,
  title: "Case study coming soon",
  industry: "Coming soon",
  summary: "Another Cerato Systems customer story will be shared here soon.",
  coverLabel: "CASE STUDY COMING SOON",
  facts: [],
  sections: [],
  outcome: null,
  closing: null,
}];
export const getCaseStudy = (slug) => caseStudies.find((study) => study.slug === slug);
